### ISSUE TITLE
Link to Github Source is wrong

### ISSUE THREAD

**Issue by Xaratas** [ragingwind/polymer-samples#2]
Thanks for your samples. They are helpful for me and many others.
I have found that the links to github are wrong. They point to samples folder which doesn't exist.

Link on the github io page:
https://github.com/ragingwind/polymer-samples/blob/master/samples/custom-css-properties-with-apply.html

Actual link to github:
https://github.com/ragingwind/polymer-samples/blob/master/demo/custom-css-properties-with-apply.html

**Comment by ragingwind** [comment]
Thanks, close it https://github.com/ragingwind/polymer-samples/commit/7ee085df263fc66b8cbdb960b59dcb6f60e30c28
